version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.7

    working_directory: ~/ma-perma-api

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run: npm test

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "StrictHostKeyChecking no" > ~/.ssh/config
              chmod 400 ~/.ssh/config
              npm run deploy:production
            else
              echo "Not master branch so not deploying"
            fi
