module.exports.FLOWER_RELATION_TYPES = [
  'ASSOCIATE_WITH',
  'DONT_ASSOCIATE_WITH',
  'DONT_PRECEDE'
]

module.exports.FLOWER_TYPES = [
  'VIVACE',
  'ANNUELLE',
  'GRIMPANTE',
  'BISANNUELLE',
  'ANNUELLE / BISANNUELLE',
  'BISANNUELLE / TRISANNUELLE',
  'ANNUELLE / VIVACE',
  'ARBUSTE OU ARBRISSEAU',
  'VIVACE / ARBUSTE OU ARBRISSEAU',
  'BISANNUELLE / VIVACE',
  'ANNUELLE / GRIMPANTE',
  'VIVACE / GRIMPANTE'
]

module.exports.PROPERTY_TYPES = [
  'CALENDAR',
  'DESCRIPTION',
  'USAGE',
  'ENVIRONMENT'
]
